# GitLab CI/CD Pipeline Configuration
# -----------------------------------
# Author/Maintainer: Alessandro Gomes
# Core Automation Team
# Last Update: 2025-05-19

stages:
  - Business Line

# Each job should be used for a business line. Each business line can have one or more YML files

MS Edge Demo:
  stage: Business Line
  trigger:
    include: "gitlab-ci/edge.yml"
    strategy: depend
  rules:
    - if: "$CI_COMMIT_REF_NAME == 'Develop' || $CI_COMMIT_REF_NAME == 'master'"
      when: never
    - when: manual