apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.name}}
spec:
  template:
    metadata:
      name: {{.Values.name}}
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: counter
        image: {{.Values.image}}
        volumeMounts:
        - name: www-data
          mountPath: /tmp/project
        command: ["/bin/sh"]
        args: ["-c","katalonc.sh -projectPath=/tmp/project -browserType='Chrome' -testSuiteCollectionPath='Test Suites/TS_RegressionTestCollection' -apiKey={{.Values.apiKey}}"]
      initContainers:
      - name: git-cloner
        image: alpine/git
        args:
            - clone
            - --single-branch
            - --
            - https://github.com/katalon-studio-samples/ci-samples
            - /data
        volumeMounts:
        - mountPath: /data
          name: www-data
      volumes:
      - name: www-data
        emptyDir: {}
      restartPolicy: Never
